### ISSUE TITLE
Exception when trying to open .efmodel file

### ISSUE THREAD

**Issue by TheMegaMatt** [msawczyn/EFDesigner#2]
![image](https://user-images.githubusercontent.com/2596849/36040614-456387b2-0dc6-11e8-9a1f-ab73cff4063a.png)

after freshly creating a newmodel this message appears

**Comment by msawczyn** [comment]
@TheMegaMatt I haven't seen this happen, so I'll need a bit more detail to track this down. 

- What kind of project were you working with (i.e., class library, asp.net app, asp.net core app, etc.)? 

- Do I understand correctly that the error occurred when trying to open an empty .efmodel file? 

- Is there any chance you could submit a visual studio log file with the error in it?

**Comment by TheMegaMatt** [comment]
I tried different project types and different version of EF (Core and full .net) Always getting the same problem.

After a bit of digging this is what i discovered inspecting the error

Errors were generated when initializing the transformation object. The transformation will not be run.  The following Exception was thrown:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Sawczyn.EFDesigner.EFModel.ModelRoot' threw an exception. ---> System.NotImplementedException: The culture 'Italian (Italy)' is not supported.   Pluralization is currently only supported for the English language.
   at System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(CultureInfo culture)
   at Sawczyn.EFDesigner.EFModel.ModelRoot..cctor()
   --- End of inner exception stack trace ---
   at Sawczyn.EFDesigner.EFModel.EFModelSerializationBehaviorBase.get_AllSerializers()
   at Microsoft.VisualStudio.Modeling.DomainXmlSerializerDirectory.InternalAddBehavior(DomainXmlSerializationBehavior serializationBehavior, Boolean resetSerializers)
   at Sawczyn.EFDesigner.EFModel.EFModelSerializationHelperBase.InitializeSerialization(Store store)
   at Sawczyn.EFDesigner.EFModel.EFModelDomainModel..ctor(Store store)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Microsoft.VisualStudio.Modeling.DomainModelReflector.ReflectDomainModel(Type type)
   at Microsoft.VisualStudio.Modeling.DomainModelReflector.ReflectDomainModels(List`1 domainModelTypes)
   at Microsoft.VisualStudio.Modeling.DomainModelReflector.ReflectModels(Store store, IEnumerable`1 domainModelTypes)
   at Microsoft.VisualStudio.Modeling.Store.LoadDomainModels(Type[] domainModelTypes)
   at Microsoft.VisualStudio.TextTemplating.VSHost.ModelingTextTransformation.Initialize()
   at Microsoft.VisualStudio.TextTemplating0E26A984CFF399DD130D803F6D8C50910442E708F29573B4DEA42927F66B5C5ACF5FD8E4D6AD2A92458FE2B0AE3687E3A9E66A3AF004C8EBD83119148AD4B05E.GeneratedTextTransformation.Initialize() in C:\Users\matte\Documents\Projects\IRSAM.Studio\IRSAM.Studio\Model\EFModel1.tt:line 29
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()	

Apparentlly i cant use it since my PC is set to italian?	


Da: Michael Sawczyn
Inviato: mercoledì 7 marzo 2018 09:26
A: msawczyn/EFDesigner
Cc: Matteo Murdocco; Mention
Oggetto: Re: [msawczyn/EFDesigner] Exception when trying to open .efmodel file(#2)

@TheMegaMatt I haven't seen this happen, so I'll need a bit more detail to track this down.
• What kind of project were you working with (i.e., class library, asp.net app, asp.net core app, etc.)?
• Do I understand correctly that the error occurred when trying to open an empty .efmodel file?
• Is there any chance you could submit a visual studio log file with the error in it?

**Comment by msawczyn** [comment]
@TheMegaMatt That's exactly what I needed ... thanks! I'll get that corrected within the next few days.

**Comment by msawczyn** [comment]
@TheMegaMatt please download 1.0.3.6.Beta1 (prerelease build) to see if it addresses your issue. Should be fixed.

**Comment by msawczyn** [comment]
Fixed as of v1.0.3.7
