### ISSUE TITLE
NotImplementedException CultureInfo 

### ISSUE THREAD

**Issue by wh1sp3r** [msawczyn/EFDesigner#29]
Hi, I found a problem with the template. It tries to use my culture to do pluralization, but ended with a not implemented exception.

"Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.NotImplementedException: The culture 'Czech (Czech Republic)' is not supported.   Pluralization is currently only supported for the English language.
   at System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(CultureInfo culture)
   at Microsoft.VisualStudio.TextTemplatingB1FB882D6FB23F37E071FAC15F790DB3D6CCE1885B7AE52C82326C4BE71A35610CEBC0A8943C91E048871F39722244F659C14ECF1A0B2A1C98B8AC0ACC30204E.GeneratedTextTransformation.WriteDbContextEFCore(ModelRoot modelRoot) in c:\program files (x86)\microsoft visual studio 2017\common7\ide\extensions\ljdqezoc.usq\TextTemplates\EFCoreDesigner.ttinclude:line 134
   at Microsoft.VisualStudio.TextTemplatingB1FB882D6FB23F37E071FAC15F790DB3D6CCE1885B7AE52C82326C4BE71A35610CEBC0A8943C91E048871F39722244F659C14ECF1A0B2A1C98B8AC0ACC30204E.GeneratedTextTransformation.GenerateEFCore(Manager manager, ModelRoot modelRoot) in c:\program files (x86)\microsoft visual studio 2017\common7\ide\extensions\ljdqezoc.usq\TextTemplates\EFCoreDesigner.ttinclude:line 42
   at Microsoft.VisualStudio.TextTemplatingB1FB882D6FB23F37E071FAC15F790DB3D6CCE1885B7AE52C82326C4BE71A35610CEBC0A8943C91E048871F39722244F659C14ECF1A0B2A1C98B8AC0ACC30204E.GeneratedTextTransformation.TransformText() in C:\Merz\Projekty\Git\CM\Magna.CM\Magna.CM.Database\DatabaseModel.tt:line 44	Miscellaneous Files	c:\program files (x86)\microsoft visual studio 2017\common7\ide\extensions\ljdqezoc.usq\TextTemplates\EFCoreDesigner.ttinclude	134	
"

Could you please catch the exception and force english pluralization ? Thank you !

**Comment by msawczyn** [comment]
Thanks for the catch! We had a pluralization issue in the past, and I thought it had been fixed ... clearly not :-(

The fix will be in the next release.

**Comment by wh1sp3r** [comment]
Hi !
I just did the quick fix and it shows an error on the line 134 in EFCoreDesigner.ttinclude

Error		Compiling transformation: Member 'ModelRoot.PluralizationService' cannot be accessed with an instance reference; qualify it with a type name instead	Miscellaneous Files	c:\program files (x86)\microsoft visual studio 2017\common7\ide\extensions\ljdqezoc.usq\TextTemplates\EFCoreDesigner.ttinclude	134

**Comment by wh1sp3r** [comment]
Hi! I did a quick fix and I got an error on line 134 in EFCoreDesigner.ttinclude

Line 134: PluralizationService pluralizationService = modelRoot.PluralizationService;
Error: Compiling transformation: Member 'ModelRoot.PluralizationService' cannot be accessed with an instance reference; qualify it with a type name instead	Miscellaneous Files	c:\program files (x86)\microsoft visual studio 2017\common7\ide\extensions\ljdqezoc.usq\TextTemplates\EFCoreDesigner.ttinclude	134

**Comment by wh1sp3r** [comment]
Ah, yes, it's because modelRoot is a instance, but PluralizationService is a static member of ModelRoot, so ModelRoot.PluralizationService fixes it.

**Comment by msawczyn** [comment]
Rats. Typo. Sorry. :-(

Since that fixes it for you, I'll go ahead and close this since that fix will be in the release.
