### ISSUE TITLE
I can't open my schema anymore with the latest version of visual studio 2022 17.7.4.

### ISSUE THREAD

**Issue by KarlRichard** [msawczyn/EFDesigner#340]
I can't open any schema anymore with the latest version of visual studio:

Microsoft Visual Studio Professional 2022 (2) (64-bit) - Current
Version 17.7.4

Entity Framework Visual Editor Extension
Version 4.2.5.1

I ask two of my co-worker and they can open the file but they are not on the latest version of visual studio 2022.

Error message:

An error occurred while initializing the frame's content
System.Runtime.InteropServices.COMException (0x8000000A): The data necessary to complete this operation is not yet available. (Exception from HRESULT: 0x8000000A)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Modeling.Shell.MonitorSelectionService.get_CurrentDocumentView()
   at Microsoft.VisualStudio.Modeling.Shell.MonitorSelectionService..ctor(IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.Modeling.Shell.AsyncModelingPackage.OnCreateService(IServiceContainer serviceContainer, Type serviceType)
   at Microsoft.VisualStudio.Shell.NullOnRecursionLazy.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Shell.NullOnRecursionLazy.ThrowIfFaulted()
   at Microsoft.VisualStudio.Shell.NullOnRecursionLazy.get_Value()
   at Microsoft.VisualStudio.Shell.Package.GetService(Type serviceType)
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
   at Microsoft.VisualStudio.Modeling.Shell.ModelingDocView.Initialize()
   at Microsoft.VisualStudio.Shell.WindowPane.InternalSetSite(IServiceProvider p)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.SetSite(DocumentObjectSite site)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.InitializeDocumentSite(Boolean creatingStubFrame, Boolean replacingStubView, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)

Thanks

**Comment by KarlRichard** [comment]
Somehow started to work.  Sorry.
