### ISSUE TITLE
InvalidCastException in MultipleOutputHelper.ttinclude

### ISSUE THREAD

**Issue by ilikebuttons** [msawczyn/EFDesigner#54]
Hi, this is my first time submitting an issue on Github so let me know if I did anything wrong or if I need to provide more information.

I have a model with about 40 entities I've been designing and not sure when the error first showed up. I'm not even sure its really even a problem since I haven't looked over the code yet, but I started a new solution just to test and the error showed after saving the second entity. Didn't resolve after deleting the second entity, so hit ctrl-z unitl it was an empty canvas, and deleted the generated code for those entities and its still there.

Running transformation: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'EnvDTE.ProjectItem'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0B48100A-473E-433C-AB8F-66B9739AB620}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.TextTemplating3246E923D3EAE737EADEB8472DF30160C46F1C6A28C09523326DEB23229A387D8DA775DCCD37FC548552E35F5D34C0A8931C74294263E74318F0438421180078.GeneratedTextTransformation.Manager.VSManager.GetCurrentState() in c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\rr1dks0x.21c\TextTemplates\MultipleOutputHelper.ttinclude:line 303
   at Microsoft.VisualStudio.TextTemplating3246E923D3EAE737EADEB8472DF30160C46F1C6A28C09523326DEB23229A387D8DA775DCCD37FC548552E35F5D34C0A8931C74294263E74318F0438421180078.GeneratedTextTransformation.Manager.VSManager.ProjectSync(IEnumerable`1 keepFileNames) in c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\rr1dks0x.21c\TextTemplates\MultipleOutputHelper.ttinclude:line 246
   at Microsoft.VisualStudio.TextTemplating3246E923D3EAE737EADEB8472DF30160C46F1C6A28C09523326DEB23229A387D8DA775DCCD37FC548552E35F5D34C0A8931C74294263E74318F0438421180078.GeneratedTextTransformation.Manager.VSManager.Process(Boolean split) in c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\rr1dks0x.21c\TextTemplates\MultipleOutputHelper.ttinclude:line 174
   at Microsoft.VisualStudio.TextTemplating3246E923D3EAE737EADEB8472DF30160C46F1C6A28C09523326DEB23229A387D8DA775DCCD37FC548552E35F5D34C0A8931C74294263E74318F0438421180078.GeneratedTextTransformation.TransformText() in C:\Users\vaultboy\source\repos\LoadoutBuilder\LoadoutBuilderClasses\LoadoutBuilderModel.tt:line 50	Miscellaneous Files	c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\rr1dks0x.21c\TextTemplates\MultipleOutputHelper.ttinclude	303

**Comment by msawczyn** [comment]
That's usually an issue with Visual Studio's `EnvDTE` assembly failing to load correctly. That's not an assembly that ships with the designer, but rather is part of the Visual Studio installation, and is showing up in the T4 you mention because it uses `EnvDTE` to do some of its work. The key is the error `No such interface supported` -- the interface in question is `ProjectItem`, which would be really bad if not supported in Visual Studio itself. 😄 

What version of Visual Studio are you using and what type of project are you working on when this happens?

**Comment by ilikebuttons** [comment]
Just a class library project. I did Add New Item --> EFDesigner, and that's the only thing I added. Visual Studio Enterprise 2017 Version 15.9.4.

**Comment by msawczyn** [comment]
Let's see if we can't get you going. 

The first thing I'd try is to uninstall the designer, close Visual Studio, reopen and reinstall the designer. Things can go awry during installation, so that's a bit of low hanging fruit to try to see if it makes a difference.

If nothing changes, grab the source code from the GitHub repository here. In the `src/Testing` directory you'll see `Testing.sln`. Open that and see if you can manipulate the models there.

Please let me know the results.

**Comment by ilikebuttons** [comment]
Apparently the issue has resolved itself! Thanks for the help.
