### ISSUE TITLE
EFModel exception in VS 2019

### ISSUE THREAD

**Issue by GarthOrmsby** [msawczyn/EFDesigner#57]
The Designer does not run in VS2019 (preview 3) - looks like the VisualStudio Modelling SDK dependency needs updated to 2019 (v16):

An Exception was thrown while processing a directive named 'EFModel'. The transformation will not be run.  The following Exception was thrown:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Modeling.Sdk.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Modeling.Sdk.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Sawczyn.EFDesigner.EFModel.EFModelDirectiveProcessorBase.GeneratePostInitializationCode(String directiveName, StringBuilder codeBuffer, CodeDomProvider languageProvider, IDictionary`2 requiresArguments, IDictionary`2 providesArguments)
   at Microsoft.VisualStudio.TextTemplating.RequiresProvidesDirectiveProcessor.ProcessDirective(String directiveName, IDictionary`2 arguments)
   at Microsoft.VisualStudio.TextTemplating.Engine.ProcessCustomDirectives(ITextTemplatingEngineHost host, TemplateProcessingSession session, IEnumerable`1 directivesToBeProcessed)

Are you able to make the extension sensitive to the target VS version?

Regards
Garth

**Comment by msawczyn** [comment]
Hi Garth.

Yes, it has yet to be undated. I'll be doing that here shortly, as soon as I can get my hands on a copy of the 2019 DSL Tools version.

Thanks for the report.

**Comment by msawczyn** [comment]
1.2.7 pre-release is in the releases. Could you take a peek and see if this resolves your issue? Note that there are still some issues with VS 2019 concerning the new project format, but those are currently out of my hands.

**Comment by msawczyn** [comment]
Fixed and released in 1.2.7.1. Closing issue.
