### ISSUE TITLE
An Error When I save *.efmodel file.

### ISSUE THREAD

**Issue by edtim8** [msawczyn/EFDesigner#96]
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sawczyn.EFDesigner.EFModel.EFModelDocData.GetEFVersionDetails(ModelRoot modelRoot)
   at Sawczyn.EFDesigner.EFModel.EFModelDocData.EnsureCorrectNuGetPackages(ModelRoot modelRoot, Boolean force)
   at Sawczyn.EFDesigner.EFModel.EFModelDocData.OnDocumentSaved(EventArgs e)
   at Microsoft.VisualStudio.Modeling.Shell.DocData.SaveDocData(VSSAVEFLAGS flags, String& fileName, Int32& saveCanceled)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass685_0.<<SaveItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass571_0.<<HrMutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass568_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )

**Comment by msawczyn** [comment]
I can't reproduce this in either the current nor development releases. If you would be able to make available a simple model file that exhibits the behavior I'd be happy to investigate further.

**Comment by msawczyn** [comment]
Closing since there's been no activity.
